# Data Analysis with Pandas Activity
This notebook contains the analysis of global suicide data.

In [1]:
import pandas as pd 
import os

ModuleNotFoundError: No module named 'pandas'

## Activity 1 (Country, Year, Age, Sex, Suicide)

In [4]:

file_path = "suicide.csv"

# Read the CSV
df = pd.read_csv(file_path)
print(df[['country', 'year', 'sex', 'age', 'suicides/100k pop']])
print(df[['country', 'year', 'sex', 'age', 'suicides/100k pop']])

          country  year     sex          age  suicides/100k pop
0         Albania  1987    male  15-24 years               6.71
1         Albania  1987    male  35-54 years               5.19
2         Albania  1987  female  15-24 years               4.83
3         Albania  1987    male    75+ years               4.59
4         Albania  1987    male  25-34 years               3.28
...           ...   ...     ...          ...                ...
27815  Uzbekistan  2014  female  35-54 years               2.96
27816  Uzbekistan  2014  female    75+ years               2.58
27817  Uzbekistan  2014    male   5-14 years               2.17
27818  Uzbekistan  2014  female   5-14 years               1.67
27819  Uzbekistan  2014  female  55-74 years               1.46

[27820 rows x 5 columns]
          country  year     sex          age  suicides/100k pop
0         Albania  1987    male  15-24 years               6.71
1         Albania  1987    male  35-54 years               5.19
2         Albania  1987  female  15-24 years               4.83
3         Albania  1987    male    75+ years               4.59
4         Albania  1987    male  25-34 years               3.28
...           ...   ...     ...          ...                ...
27815  Uzbekistan  2014  female  35-54 years               2.96
27816  Uzbekistan  2014  female    75+ years               2.58
27817  Uzbekistan  2014    male   5-14 years               2.17
27818  Uzbekistan  2014  female   5-14 years               1.67
27819  Uzbekistan  2014  female  55-74 years               1.46

[27820 rows x 5 columns]

## Activity 2 Suicide record. Display year, sex, age, suicides_n, and suicides/100k pop columns.

In [7]:
ph_records = df[df['country'] == 'Philippines']
display(ph_records[['year', 'sex', 'age', 'suicides_no', 'suicides/100k pop']])

ph_2011 = df[(df['country'] == 'Philippines') & (df['year'] == 2011)]
ph_2011[['year', 'sex', 'age', 'suicides_no', 'suicides/100k pop']]

       year     sex          age  suicides_no  suicides/100k pop
18888  1992    male    75+ years            6               2.26
18889  1992    male  55-74 years           26               1.43
18890  1992    male  25-34 years           66               1.30
18891  1992    male  15-24 years           86               1.30
18892  1992    male  35-54 years           60               1.07
...     ...     ...          ...          ...                ...
19063  2011  female  25-34 years          120               1.67
19064  2011  female  35-54 years          147               1.44
19065  2011  female  55-74 years           39               0.90
19066  2011    male   5-14 years           44               0.41
19067  2011  female   5-14 years           29               0.29

[180 rows x 5 columns]

       year     sex          age  suicides_no  suicides/100k pop
19056  2011    male    75+ years           64              12.97
19057  2011    male  25-34 years          470               6.37
19058  2011    male  55-74 years          227               5.84
19059  2011    male  15-24 years          541               5.70
19060  2011    male  35-54 years          533               5.12
19061  2011  female  15-24 years          221               2.41
19062  2011  female    75+ years           14               1.79
19063  2011  female  25-34 years          120               1.67
19064  2011  female  35-54 years          147               1.44
19065  2011  female  55-74 years           39               0.90
19066  2011    male   5-14 years           44               0.41
19067  2011  female   5-14 years           29               0.29

## Activity 3 Suicide record in the year 2011. Display year, sex, age, suicides_n, and suicides/100k pop columns

In [10]:
ph_2011 = df[(df['country'] == 'Philippines') & (df['year'] == 2011)]
display(ph_2011[['year', 'sex', 'age', 'suicides_no', 'suicides/100k pop']])

       year     sex          age  suicides_no  suicides/100k pop
19056  2011    male    75+ years           64              12.97
19057  2011    male  25-34 years          470               6.37
19058  2011    male  55-74 years          227               5.84
19059  2011    male  15-24 years          541               5.70
19060  2011    male  35-54 years          533               5.12
19061  2011  female  15-24 years          221               2.41
19062  2011  female    75+ years           14               1.79
19063  2011  female  25-34 years          120               1.67
19064  2011  female  35-54 years          147               1.44
19065  2011  female  55-74 years           39               0.90
19066  2011    male   5-14 years           44               0.41
19067  2011  female   5-14 years           29               0.29

## Activity 4 Country with the highest suicide per 100k population in 2005.Display year, sex, age, and suicides/100k pop columns.

In [11]:
highest_2005 = df[df['year'] == 2005].sort_values(by='suicides/100k pop', ascending=False).head(1)
display(highest_2005[['country', 'year', 'sex', 'age', 'suicides/100k pop']])

                 country  year   sex        age  suicides/100k pop
20470  Republic of Korea  2005  male  75+ years             176.33

## Activity 5 Total suicide cases (suicides_n) and suicides/100k pop per year. Sort in descending order based on suicides_n.

In [12]:
year_stats = df.groupby('year').agg({'suicides_no': 'sum', 'suicides/100k pop': 'sum'})
display(year_stats.sort_values(by='suicides_no', ascending=False))

      suicides_no  suicides/100k pop
year
1999       256119           14473.91
2002       256095           14227.72
2003       256079           13627.58
2000       255832           14387.45
2001       250652           14276.21
1998       249591           14150.72
1996       246725           14142.21
1995       243544           14660.26
2009       243487           12176.04
2004       240861           12581.80
1997       240745           13817.83
2010       238702           11843.99
2011       236484           11367.84
2008       235447           12145.84
2005       234375           12164.99
2007       233408           12410.15
2006       233361           12166.01
1994       232063           11483.79
2012       230160           11101.91
2013       223199           10663.64
2014       222984           10306.73
1993       221565           10790.29
1992       211473           10528.88
2015       203640            8253.99
1991       198020           10321.06
1990       193361            9878.75
1989       160244            8036.54
1987       126842            7545.45
1988       121026            7473.13
1986       120670            6579.84
1985       116063            6811.89
2016        15603            2147.39

## Activity 6 total suicide cases (suicides_n) and suicides/100k pop per gender. Sort in descending order based on suicides_n.

In [ ]:
gender_stats = df.groupby('sex').agg({'suicides_no': 'sum', 'suicides/100k pop': 'sum'})
display(gender_stats.sort_values(by='suicides_no', ascending=False))

        suicides_no  suicides/100k pop
sex
male        5188910          281529.06
female      1559510           75014.77

## Activity 7 Total suicide cases (suicides_n) and suicides/100k pop per age. Sort in descending order based on suicides_n.

In [ ]:
age_stats = df.groupby('age').agg({'suicides_no': 'sum', 'suicides/100k pop': 'sum'})
display(age_stats.sort_values(by='suicides_no', ascending=False))

             suicides_no  suicides/100k pop
age
35-54 years      2452141           69386.02
55-74 years      1658443           74994.20
25-34 years      1123912           56571.52
15-24 years       808542           41532.69
75+ years         653118          111201.01
5-14 years         52264            2858.39

## Activity 8 Total suicide cases (suicides_n) per country and per year. Sort in descending order based on suicides_n.

In [18]:
country_year_stats = df.groupby(['country', 'year'])[['suicides_no']].sum()
display(country_year_stats.sort_values(by='suicides_no', ascending=False))

                          suicides_no
country             year
Russian Federation  1994        61420
                    1995        60548
                    1996        57511
                    1999        56974
                    2001        56958
...                               ...
Antigua and Barbuda 2012            0
                    1991            0
                    1989            0
Saint Lucia         2008            0
Antigua and Barbuda 1992            0

[2321 rows x 1 columns]

## Activity 9 Total suicide cases in the Philippines based on year, gender, and age.

In [19]:
ph_total_stats = df[df['country'] == 'Philippines'].groupby(['year', 'sex', 'age'])[['suicides_no']].sum()
display(ph_total_stats)

                         suicides_no
year sex    age
1992 female 15-24 years           57
            25-34 years           16
            35-54 years           21
            5-14 years             0
            55-74 years            7
...                              ...
2011 male   25-34 years          470
            35-54 years          533
            5-14 years            44
            55-74 years          227
            75+ years             64

[180 rows x 1 columns]

## Activity 10 year and number of suicide cases that the Philippines has the highest number of combined suicide cases.

In [20]:
ph_highest_year = df[df['country'] == 'Philippines'].groupby('year')[['suicides_no']].sum()
display(ph_highest_year.sort_values(by='suicides_no', ascending=False).head(1))

      suicides_no
year
2011         2449